"""new fields in user modal

Revision ID: f1b1f9530343
Revises: 0569e41915ae
Create Date: 2020-02-04 22:13:01.451491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b1f9530343'
down_revision = '0569e41915ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
